server:
  port: 9999
  tomcat:
    max-http-form-post-size: 10MB


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/petrichor
    username: root
    password: 123456
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
  output:
    ansi:
      enabled: ALWAYS
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:/mapper/*.xml

pagehelper:
  reasonable: false
  defaultCount: true

petrichor:
  token:
    ex: 3600

# noinspection undefined
# noinspection PropertyRemoved
logging:
  file:
    name: logs/spring.log
  level:
    root: INFO
#    com.petrichor.sincerity.mapper: DEBUG
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.log
      max-file-size: 1MB
      max-history: 30
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %clr(%-5level) [%thread] %logger{15} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{15} - %msg%n"

